spring.mongodb.uri=${SPRING_MONGODB_URI}
spring.mongodb.database=${SPRING_MONGODB_DATABASE}
server.port=${SERVER_PORT}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}

# Le pont vers votre variable d'environnement pour l'IA
app.services.ia-planner.url=${APP_SERVICES_IA_PLANNER}